### ISSUE TITLE
Last two code snippets produce errors and don't output markets

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/node-js-promises#5]
![image](https://cloud.githubusercontent.com/assets/15042882/16664343/8e46d87e-444d-11e6-9858-f4f03c58d3dd.png)
this occurs when either of the last two snippets are run, while when teh original snippet runs .i.e.
//queryUSDAFarmersMarkets(10004)
//  .then((respBody) => {
//    console.log('response', JSON.parse(respBody));
//  })
//  .catch((err) =>{
//    console.log('error: ', err);
//  });
it correctly outputs the marketplaces

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by pletcher** [comment]
You'll need to create the database as well -- I've added instructions for that :)
